import { describe, it, expect } from 'vitest';
import groundTruth from './excel_ground_truth.json';
import { runProjection, annualMedicareCost, ssStartYear } from '../projection';
import { defaultInputs } from '../defaults';
import type { PlanInputs } from '../types';

// Generic test inputs — plausible but not anyone's real numbers.
// The ground-truth fixture was generated by running runProjection(testInputs()) and
// capturing the output, so tests below are regression-locked to the engine's own math.
function testInputs(): PlanInputs {
  return {
    startYear: 2026,
    single: false,
    taxMode: 'simple',
    detailed: defaultInputs().detailed,
    events: [],
    withdrawalStrategy: 'fixed',
    guardrails: { band: 0.2, adjustment: 0.1 },
    you: {
      name: 'You',
      currentAge: 50,
      retirementAge: 57,
      lifeExpectancy: 90,
      annualContribution: 30000,
      contributionIncreasePct: 0.01,
      medicareEligibilityAge: 65,
      partBMonthly: 174.7,
      partDMonthly: 20.0,
      irmaaSurchargePct: 0,
      partDIrmaaMonthly: 0,
      ssStartAge: 67,
      ssAnnualBenefit: 24000,
    },
    spouse: {
      name: 'Spouse',
      currentAge: 48,
      retirementAge: 55,
      lifeExpectancy: 90,
      annualContribution: 30000,
      contributionIncreasePct: 0.01,
      medicareEligibilityAge: 65,
      partBMonthly: 174.7,
      partDMonthly: 20.0,
      irmaaSurchargePct: 0,
      partDIrmaaMonthly: 0,
      ssStartAge: 67,
      ssAnnualBenefit: 18000,
    },
    currentBalance: 1500000,
    returnAccumulation: 0.07,
    returnRetirement: 0.05,
    inflation: 0.03,
    goGoSpending: 80000,
    goGoEndAge: 72,
    slowGoReductionPct: -0.25,
    slowGoEndAge: 82,
    noGoAdditionalReductionPct: -0.10,
    preMedicarePremium: 20000,
    premiumPctAfterFirstMedicare: 0.5,
    medicarePremiumGrowth: 0.055,
    taxRatePreSS: 0.20,
    taxRatePostSS: 0.22,
    includeSS: false,
    ssColaOn: false,
    ssColaRate: 0.02,
    ssCutPct: 0.17,
    ssCutStartYear: 2035,
    inflationAdjustWithdrawals: true,
    oneTimeExpense: 0,
    oneTimeExpenseYear: 2035,
    stressTestOn: true,
    stressReturns: [-0.15, -0.05, 0, 0.08],
    ltcOn: true,
    ltcAnnualCost: 80000,
    ltcStartAge: 83,
    ltcYears: 3,
    cashReserveOn: true,
    cashReserveYears: 2,
    cashReserveYield: 0.03,
    survivorOn: false,
    yourDeathAge: 75,
    survivorSpendingChangePct: -0.25,
    survivorTaxRate: 0.25,
  };
}

// Fixture column order:
// 0 year, 1 yourAge, 2 spouseAge, 3 phase, 4 yourContrib, 5 spouseContrib,
// 6 yourSS, 7 spouseSS, 8 totalSS, 9 spending, 10 medicare, 11 preMedIns,
// 12 draw, 13 taxes(null in accumulation), 14 return, 15 begBal, 16 endBal,
// 17 onTrack, 18 spendPhase, 19 ltc, 20 cashReserve, 21 endBalReal

function close(actual: number, expected: number) {
  const tol = Math.max(Math.abs(expected) * 1e-9, 1e-6);
  expect(Math.abs(actual - expected)).toBeLessThanOrEqual(tol);
}

describe('Projection engine regression (stress + LTC + cash reserve on, SS off)', () => {
  const result = runProjection(testInputs());
  const rows = groundTruth as unknown[][];

  it('produces the same number of projection years', () => {
    expect(result.rows.length).toBe(rows.length);
  });

  it.each(rows.map((r, i) => [i, r] as const))('matches fixture row %i', (i, r) => {
    const row = result.rows[i];
    expect(row.year).toBe(r[0]);
    expect(row.yourAge).toBe(r[1]);
    expect(row.spouseAge).toBe(r[2]);
    expect(row.phase).toBe(r[3]);
    close(row.yourContribution, r[4] as number);
    close(row.spouseContribution, r[5] as number);
    close(row.totalSS, r[8] as number);
    close(row.spending, r[9] as number);
    close(row.medicare, r[10] as number);
    close(row.preMedicareInsurance, r[11] as number);
    close(row.portfolioDraw, r[12] as number);
    close(row.estimatedTaxes, (r[13] as number | null) ?? 0);
    close(row.rateOfReturn, r[14] as number);
    close(row.beginBalance, r[15] as number);
    close(row.endBalance, r[16] as number);
    close(row.ltcCost, r[19] as number);
    close(row.cashReserve, r[20] as number);
    close(row.endBalanceReal, r[21] as number);
  });

  it('matches summary values', () => {
    close(result.balanceAtRetirement!, 2942318.339089065);
    close(result.finalBalance, 0);
    expect(result.runsOut).toBe(true);
    expect(result.peakBalanceYear).toBe(2032);
    expect(result.retirementYearYou).toBe(2033);
  });
});

describe('Social Security path (hand-computed from engine formula)', () => {
  it('inflates benefit to start age, applies the funding cut, and switches tax rate', () => {
    const inputs = { ...testInputs(), includeSS: true, stressTestOn: false, ltcOn: false, cashReserveOn: false };
    const result = runProjection(inputs);
    expect(ssStartYear(inputs)).toBe(2043);
    const r2043 = result.rows.find((r) => r.year === 2043)!;
    // Your age 67 in 2043: 24000 * 1.03^17 * (1 - 0.17)  [2043 >= 2035 cut year]
    close(r2043.yourSS, 24000 * Math.pow(1.03, 17) * 0.83);
    // Spouse is 65 — hasn't started yet
    expect(r2043.spouseSS).toBe(0);
    // Post-SS tax rate 22% applies from ssStartYear on
    close(r2043.estimatedTaxes, r2043.portfolioDraw * 0.22);
    const r2042 = result.rows.find((r) => r.year === 2042)!;
    close(r2042.estimatedTaxes, r2042.portfolioDraw * 0.20);
    // Spouse starts at 67 in 2045: 18000 * 1.03^19 * 0.83
    const r2045 = result.rows.find((r) => r.year === 2045)!;
    close(r2045.spouseSS, 18000 * Math.pow(1.03, 19) * 0.83);
    close(r2045.totalSS, r2045.yourSS + r2045.spouseSS);
  });

  it('applies COLA from the start age when enabled', () => {
    const inputs = {
      ...testInputs(),
      includeSS: true,
      ssColaOn: true,
      ssCutPct: 0,
      stressTestOn: false,
      ltcOn: false,
      cashReserveOn: false,
    };
    const result = runProjection(inputs);
    const r2047 = result.rows.find((r) => r.year === 2047)!; // your age 71, 4 years of COLA after SS start
    close(r2047.yourSS, 24000 * Math.pow(1.03, 17) * Math.pow(1.02, 4));
  });
});

describe('Survivor scenario (hand-computed from engine formula)', () => {
  it('keeps larger SS benefit, reduces spending, drops your Medicare, uses survivor tax rate', () => {
    const inputs = {
      ...testInputs(),
      includeSS: true,
      survivorOn: true,
      yourDeathAge: 75,
      stressTestOn: false,
      ltcOn: false,
      cashReserveOn: false,
    };
    const result = runProjection(inputs);
    const r = result.rows.find((r) => r.yourAge === 76)!; // survivor active (>= 75)
    expect(r.totalSS).toBe(Math.max(r.yourSS, r.spouseSS));
    // Spending = slow-go mult (age 76, 1-0.25) * inflation * survivor reduction (1-0.25)
    const t = r.year - 2026;
    close(r.spending, 80000 * 0.75 * Math.pow(1.03, t) * 0.75);
    // Your Medicare stops; spouse (age 74) continues
    const spouseMed = annualMedicareCost(inputs.spouse) * Math.pow(1.055, t);
    close(r.medicare, spouseMed);
    close(r.estimatedTaxes, r.portfolioDraw * 0.25);
  });
});

describe('return overrides (Monte Carlo hook)', () => {
  it('uses supplied per-year returns', () => {
    const inputs = testInputs();
    const overrides = new Array(10).fill(0.02);
    const result = runProjection(inputs, overrides);
    expect(result.rows[0].rateOfReturn).toBe(0.02);
    expect(result.rows[9].rateOfReturn).toBe(0.02);
    // Past the overrides the normal logic resumes (year 11 = 2037, retirement phase, past stress test)
    expect(result.rows[11].rateOfReturn).toBe(inputs.returnRetirement);
  });
});
